### ISSUE TITLE
Thanks for this! Also, had a crash.

### ISSUE THREAD

**Issue by PangolinM** [Grum999/BuliCommander#2] opened 2020-10-27 21:41 UTC
Good work on this plugin! Wish the appimage had this sort of thing, but... Well, I try not to say unkind things.

Here's a traceback.
[Traceback.txt](https://github.com/Grum999/BuliCommander/files/5448237/Traceback.txt)

Happened in 4.4.0 while I was using the arrow keys to scroll through my files.

**Comment by Grum999** [comment] 2020-10-27 22:18
Hi @PangolinM 

Thanks for feedback :-) 
_Buli Commander_ is still in earlier development phase and it might be full of bug, but reported bugs are always welcome, I can't find all of them :+1: 

Concerning the crash, for what I can see in the traceback, it's related to this part of code:
```
 1733                 elif chunk['id']=='sRGB':
 1734                     returned.update(decodeChunk_sRGB(chunk))
 1735                     returned.pop('gamma')
```
It's more related to an image than the fact you've used the keys to scroll through your files.
Concerned file: `/media/mike/Data/Documents/Ar...6168a94d9b4111b2` (sorry, I don't have full file name in trace but you might be able to find it with the given filename part)

To be able to reproduce the case (and fix it), there's 2 solutions:
- I try to create/get a PNG file with the same kind of properties
- You can help by providing the file (if file content is not confidential, of course...)

Anyway, I'll try to fix this for release 0.5.0a (release 0.4.0a should be published but due to a lack of time in last weeks, it's reported and I don't want to add anything more in 0.4.0a for now)

Grum999

**Comment by Grum999** [comment] 2020-11-01 09:52
Hi @PangolinM 

I've pushed a fix for this problem (Commit https://github.com/Grum999/BuliCommander/commit/95e39007cf64c31e60eb767f677b283e9e1e438e)
But, as I don't have PNG file that generate the crash, if you can download current 0.5.0a branch and tell me if problem is really fixed, it could be great :-) 

Grum999

**Comment by Grum999** [comment] 2022-06-12 15:20
No answers about this problem, on my side I consider the problem is fixed :-) 

Closing issue

Grum999

**Closed by Grum999** 2022-06-12 15:20 UTC
Labels: bug
